export const CATEGORY_OPTIONS = [
  'Electronics',
  'Home',
  'Clothing',
  'Books',
  'Tools',
  'Appliances',
  'Toys',
  'Sports',
  'Beauty',
  'Office',
  'Other',
];

export const STATUS_OPTIONS = [
  'Active/Using',
  'Stored',
  'Lent Out',
  'Loaned (Borrowed)',
  'Under Repair',
  'Broken',
  'To Repair',
  'To Sell',
  'Sold',
  'Donated',
  'Lost',
  'Returned',
  'Warranty',
];

export const CURRENCY_PREFIX = 'RM';

// Iconify catalog (mdi collection) – 100+ item icons grouped by category
export const ICON_CATALOG = [
  { category: 'Phones & Tablets', items: [
    { label: 'Phone', id: 'mdi:cellphone' },
    { label: 'Smartphone', id: 'mdi:cellphone-android' },
    { label: 'iPhone', id: 'mdi:cellphone-iphone' },
    { label: 'Tablet', id: 'mdi:tablet' },
    { label: 'Tablet Android', id: 'mdi:tablet-android' },
    { label: 'E-Reader', id: 'mdi:tablet-cellphone' },
    { label: 'SIM Card', id: 'mdi:sim' },
    { label: 'Charger', id: 'mdi:lightning-bolt-circle' },
  ]},
  { category: 'Computers', items: [
    { label: 'Laptop', id: 'mdi:laptop' },
    { label: 'Gaming Laptop', id: 'mdi:laptop-account' },
    { label: 'Desktop', id: 'mdi:desktop-classic' },
    { label: 'Monitor', id: 'mdi:monitor' },
    { label: 'Keyboard', id: 'mdi:keyboard' },
    { label: 'Mouse', id: 'mdi:mouse' },
    { label: 'Trackpad', id: 'mdi:gesture-tap-button' },
    { label: 'Printer', id: 'mdi:printer' },
  ]},
  { category: 'Storage & Networking', items: [
    { label: 'External HDD', id: 'mdi:harddisk' },
    { label: 'SSD', id: 'mdi:harddisk' },
    { label: 'USB Drive', id: 'mdi:usb-flash-drive' },
    { label: 'Memory Card', id: 'mdi:sd' },
    { label: 'Router', id: 'mdi:router-network' },
    { label: 'Modem', id: 'mdi:access-point' },
    { label: 'Server', id: 'mdi:server' },
    { label: 'NAS', id: 'mdi:server-network' },
  ]},
  { category: 'Audio & Music', items: [
    { label: 'Headphones', id: 'mdi:headphones' },
    { label: 'Earbuds', id: 'mdi:headphones-box' },
    { label: 'Speaker', id: 'mdi:speaker' },
    { label: 'Soundbar', id: 'mdi:soundbar' },
    { label: 'Microphone', id: 'mdi:microphone' },
    { label: 'Guitar', id: 'mdi:guitar-acoustic' },
    { label: 'Piano', id: 'mdi:piano' },
    { label: 'Violin', id: 'mdi:violin' },
  ]},
  { category: 'Cameras & Imaging', items: [
    { label: 'Camera', id: 'mdi:camera' },
    { label: 'Action Cam', id: 'mdi:video' },
    { label: 'Drone', id: 'mdi:quadcopter' },
    { label: 'Tripod', id: 'mdi:camera-iris' },
    { label: 'Lens', id: 'mdi:camera-outline' },
    { label: 'Memory Card', id: 'mdi:sd' },
    { label: 'Film', id: 'mdi:film' },
    { label: 'Photo Printer', id: 'mdi:printer' },
  ]},
  { category: 'Wearables', items: [
    { label: 'Smart Watch', id: 'mdi:watch-variant' },
    { label: 'Fitness Band', id: 'mdi:watch' },
    { label: 'Glasses', id: 'mdi:glasses' },
    { label: 'VR Headset', id: 'mdi:virtual-reality' },
    { label: 'Camera Strap', id: 'mdi:lanyard' },
    { label: 'Wallet', id: 'mdi:wallet' },
    { label: 'Key', id: 'mdi:key-variant' },
    { label: 'Umbrella', id: 'mdi:umbrella' },
  ]},
  { category: 'Home Appliances', items: [
    { label: 'Fridge', id: 'mdi:fridge' },
    { label: 'Washing Machine', id: 'mdi:washing-machine' },
    { label: 'Dryer', id: 'mdi:tumble-dryer' },
    { label: 'Air Conditioner', id: 'mdi:air-conditioner' },
    { label: 'Heater', id: 'mdi:radiator' },
    { label: 'Vacuum', id: 'mdi:vacuum' },
    { label: 'Fan', id: 'mdi:fan' },
    { label: 'Water Heater', id: 'mdi:water-boiler' },
  ]},
  { category: 'Kitchen', items: [
    { label: 'Microwave', id: 'mdi:microwave' },
    { label: 'Oven', id: 'mdi:stove' },
    { label: 'Toaster', id: 'mdi:toaster' },
    { label: 'Coffee Maker', id: 'mdi:coffee-maker' },
    { label: 'Kettle', id: 'mdi:kettle' },
    { label: 'Blender', id: 'mdi:blender' },
    { label: 'Rice Cooker', id: 'mdi:rice' },
    { label: 'Air Fryer', id: 'mdi:chef-hat' },
  ]},
  { category: 'Furniture', items: [
    { label: 'Sofa', id: 'mdi:sofa' },
    { label: 'Bed', id: 'mdi:bed' },
    { label: 'Desk', id: 'mdi:desk' },
    { label: 'Chair', id: 'mdi:chair-rolling' },
    { label: 'Wardrobe', id: 'mdi:wardrobe' },
    { label: 'Bookshelf', id: 'mdi:book' },
    { label: 'Table', id: 'mdi:table' },
    { label: 'Mirror', id: 'mdi:mirror' },
  ]},
  { category: 'Tools & Hardware', items: [
    { label: 'Toolbox', id: 'mdi:toolbox' },
    { label: 'Hammer & Wrench', id: 'mdi:hammer-wrench' },
    { label: 'Screwdriver', id: 'mdi:screwdriver' },
    { label: 'Wrench', id: 'mdi:wrench' },
    { label: 'Pliers', id: 'mdi:pliers' },
    { label: 'Saw', id: 'mdi:hand-saw' },
    { label: 'Drill', id: 'mdi:drill' },
    { label: 'Tape Measure', id: 'mdi:tape-measure' },
  ]},
  { category: 'Office & Stationery', items: [
    { label: 'Notebook', id: 'mdi:notebook' },
    { label: 'Pen', id: 'mdi:pen' },
    { label: 'Pencil', id: 'mdi:pencil' },
    { label: 'Paperclip', id: 'mdi:paperclip' },
    { label: 'Stapler', id: 'mdi:stapler' },
    { label: 'Calculator', id: 'mdi:calculator' },
    { label: 'Scanner', id: 'mdi:scanner' },
    { label: 'Shredder', id: 'mdi:shredder' },
  ]},
  { category: 'Clothing & Accessories', items: [
    { label: 'T-Shirt', id: 'mdi:tshirt-crew' },
    { label: 'Hoodie', id: 'mdi:hoodie' },
    { label: 'Pants', id: 'mdi:human-male' },
    { label: 'Dress', id: 'mdi:human-female' },
    { label: 'Sneakers', id: 'mdi:shoe-sneaker' },
    { label: 'Watch', id: 'mdi:watch-variant' },
    { label: 'Glasses', id: 'mdi:glasses' },
    { label: 'Backpack', id: 'mdi:bag-personal' },
  ]},
  { category: 'Sports & Fitness', items: [
    { label: 'Dumbbell', id: 'mdi:dumbbell' },
    { label: 'Yoga Mat', id: 'mdi:yoga' },
    { label: 'Bicycle', id: 'mdi:bicycle' },
    { label: 'Basketball', id: 'mdi:basketball' },
    { label: 'Football', id: 'mdi:football' },
    { label: 'Soccer', id: 'mdi:soccer' },
    { label: 'Tennis', id: 'mdi:tennis' },
    { label: 'Badminton', id: 'mdi:badminton' },
  ]},
  { category: 'Outdoor & Travel', items: [
    { label: 'Tent', id: 'mdi:tent' },
    { label: 'Campfire', id: 'mdi:campfire' },
    { label: 'Flashlight', id: 'mdi:flashlight' },
    { label: 'Lantern', id: 'mdi:lantern' },
    { label: 'Compass', id: 'mdi:compass' },
    { label: 'Binoculars', id: 'mdi:binoculars' },
    { label: 'Suitcase', id: 'mdi:suitcase' },
    { label: 'Water Bottle', id: 'mdi:bottle-soda' },
  ]},
  { category: 'Toys & Games', items: [
    { label: 'Toy Brick', id: 'mdi:toy-brick' },
    { label: 'Puzzle', id: 'mdi:puzzle' },
    { label: 'Teddy Bear', id: 'mdi:teddy-bear' },
    { label: 'Robot', id: 'mdi:robot' },
    { label: 'Gamepad', id: 'mdi:gamepad-variant' },
    { label: 'Board Game', id: 'mdi:chess-king' },
    { label: 'Cards', id: 'mdi:cards-playing' },
    { label: 'Dice', id: 'mdi:dice-multiple' },
  ]},
  { category: 'Beauty & Personal Care', items: [
    { label: 'Hair Dryer', id: 'mdi:hair-dryer' },
    { label: 'Lipstick', id: 'mdi:lipstick' },
    { label: 'Comb', id: 'mdi:comb' },
    { label: 'Mirror', id: 'mdi:mirror' },
    { label: 'Perfume', id: 'mdi:perfume' },
    { label: 'Nail Polish', id: 'mdi:nail' },
    { label: 'Shaver', id: 'mdi:razor-double-edge' },
    { label: 'Toothbrush', id: 'mdi:toothbrush' },
  ]},
  { category: 'Health & Medical', items: [
    { label: 'Pill', id: 'mdi:pill' },
    { label: 'Bandage', id: 'mdi:bandage' },
    { label: 'Thermometer', id: 'mdi:thermometer' },
    { label: 'Stethoscope', id: 'mdi:stethoscope' },
    { label: 'First Aid', id: 'mdi:first-aid' },
    { label: 'Heart', id: 'mdi:heart-pulse' },
    { label: 'Syringe', id: 'mdi:syringe' },
    { label: 'Scale', id: 'mdi:scale-bathroom' },
  ]},
  { category: 'Automotive', items: [
    { label: 'Car', id: 'mdi:car' },
    { label: 'Car Battery', id: 'mdi:car-battery' },
    { label: 'Car Wrench', id: 'mdi:car-wrench' },
    { label: 'Gas', id: 'mdi:gas-station' },
    { label: 'Engine', id: 'mdi:engine' },
    { label: 'Oil', id: 'mdi:oil' },
    { label: 'Tire', id: 'mdi:car-tire-alert' },
    { label: 'Helmet', id: 'mdi:helmet' },
  ]},
  { category: 'Pets', items: [
    { label: 'Dog', id: 'mdi:dog' },
    { label: 'Cat', id: 'mdi:cat' },
    { label: 'Bird', id: 'mdi:bird' },
    { label: 'Fish', id: 'mdi:fishbowl' },
    { label: 'Bone', id: 'mdi:bone' },
    { label: 'Food', id: 'mdi:food-drumstick' },
    { label: 'Pet Carrier', id: 'mdi:baguette' },
    { label: 'Medicine', id: 'mdi:pill' },
  ]},
  { category: 'Cleaning & Household', items: [
    { label: 'Detergent', id: 'mdi:bottle-tonic' },
    { label: 'Broom', id: 'mdi:broom' },
    { label: 'Mop', id: 'mdi:hand-water' },
    { label: 'Bucket', id: 'mdi:bucket' },
    { label: 'Vacuum', id: 'mdi:vacuum' },
    { label: 'Trash Can', id: 'mdi:trash-can' },
    { label: 'Gloves', id: 'mdi:hand' },
    { label: 'Sponge', id: 'mdi:sponge' },
  ]},
  { category: 'Gardening', items: [
    { label: 'Shovel', id: 'mdi:shovel' },
    { label: 'Rake', id: 'mdi:rake' },
    { label: 'Watering Can', id: 'mdi:watering-can' },
    { label: 'Flower', id: 'mdi:flower' },
    { label: 'Sprout', id: 'mdi:sprout' },
    { label: 'Lawn Mower', id: 'mdi:lawn-mower' },
    { label: 'Hose', id: 'mdi:water' },
    { label: 'Pruner', id: 'mdi:scissors-cutting' },
  ]},
  { category: 'Books & Media', items: [
    { label: 'Book', id: 'mdi:book-open-variant' },
    { label: 'Magazine', id: 'mdi:book-open-page-variant' },
    { label: 'CD / DVD', id: 'mdi:disc' },
    { label: 'Vinyl', id: 'mdi:record-player' },
    { label: 'Camera Film', id: 'mdi:film' },
    { label: 'Game Cartridge', id: 'mdi:gamepad-variant' },
    { label: 'Ebook', id: 'mdi:tablet' },
    { label: 'Newspaper', id: 'mdi:newspaper-variant' },
  ]},
  { category: 'Art & Craft', items: [
    { label: 'Paint Brush', id: 'mdi:brush' },
    { label: 'Palette', id: 'mdi:palette' },
    { label: 'Scissors', id: 'mdi:scissors-cutting' },
    { label: 'Glue', id: 'mdi:bottle-soda' },
    { label: 'Needle', id: 'mdi:needle' },
    { label: 'Thread', id: 'mdi:thread' },
    { label: 'Sewing Machine', id: 'mdi:sewing-machine' },
    { label: 'Beads', id: 'mdi:circle-multiple' },
  ]},
  { category: 'Lighting & Electrical', items: [
    { label: 'Lightbulb', id: 'mdi:lightbulb-on' },
    { label: 'LED Strip', id: 'mdi:led-strip-variant' },
    { label: 'Power Strip', id: 'mdi:power-socket' },
    { label: 'Extension Cord', id: 'mdi:cable-data' },
    { label: 'Battery', id: 'mdi:battery' },
    { label: 'Solar Panel', id: 'mdi:solar-panel' },
    { label: 'Smart Plug', id: 'mdi:power-plug' },
    { label: 'Smart Bulb', id: 'mdi:lightbulb-cfl-spiral' },
  ]},
  { category: 'Miscellaneous', items: [
    { label: 'Gift', id: 'mdi:gift' },
    { label: 'Safe', id: 'mdi:safe' },
    { label: 'Lock', id: 'mdi:lock' },
    { label: 'Tool Belt', id: 'mdi:toolbox-outline' },
    { label: 'Clock', id: 'mdi:clock-outline' },
    { label: 'Calendar', id: 'mdi:calendar' },
    { label: 'Map', id: 'mdi:map' },
    { label: 'Tag', id: 'mdi:tag' },
  ]},
];

export function iconUrlForId(id) {
  return `https://api.iconify.design/${id}.svg`;
}


